In [6]:
import numpy as np

In [7]:
a = np.array(([1, 2], [3, 4]))
b = np.array(([5, 6], [7, 8]))

In [8]:
print("Multiplication \n", a.dot(b))
print("Transpose \n", a.transpose())
print("Flattened (1D) \n", a.flatten())
print("Inverse \n", np.linalg.inv(a))
print("Determinant \n", np.linalg.det(a))


Multiplication 
 [[19 22]
 [43 50]]
Transpose 
 [[1 3]
 [2 4]]
Flattened (1D) 
 [1 2 3 4]
Inverse 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant 
 -2.0000000000000004


In [9]:
# Read a matrix
rows = int(input("Enter the number of rows: "))
cols = int(input("Enter the number of cols: "))
m = [[int(input("Element: ")) for _ in range(cols)] for _ in range(rows)]
print(m)

[[1, 2]]


Write a python program to create two matrices (Take values from the user) and find the following:
- Dot Product
- Transpose
- Determinant
- Inverse
- Trace
- Rank
- Eigenvalues and Eigenvectors

In [14]:
# Read 2 matrices
m1 = int(input("Enter the number of rows: "))
n1 = int(input("Enter the number of cols: "))
matrix1 = np.asarray([np.asarray([int(input("Element: ")) for _ in range(n1)]) for _ in range(m1)])

m2 = int(input("Enter the number of rows: "))
n2 = int(input("Enter the number of cols: "))
matrix2 = np.asarray([np.asarray([int(input("Element: ")) for _ in range(n2)]) for _ in range(m2)])

print (matrix1)
print (matrix2)

[[1 2]
 [3 4]]
[[ 4  8]
 [16 32]]


In [15]:
# Dot Product
matrix1.dot(matrix2)

array([[ 36,  72],
       [ 76, 152]])

In [17]:
# Transpose
matrix1.transpose()

array([[1, 3],
       [2, 4]])

In [25]:
# Determinant
np.linalg.det(matrix2)

0.0

In [26]:
# Inverse
np.linalg.inv(matrix1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
# Trace
np.trace(matrix1)

5

In [29]:
# Rank
np.linalg.matrix_rank(matrix1)

2

In [32]:
# Eigenvalues and eigenvectors
np.linalg.eig(matrix1)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

In [39]:
# Read matrix
m = int(input("R: "))
n = int(input("C: "))

matrix = np.asarray([int(input("Element: ")) for _ in range(m * n)]).reshape(m, n)
print(matrix)

[[1 2 3]
 [4 5 6]]


Write a numpy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [48]:
vec = np.array(range(1, 21))
print(vec)

for i in range(8, 15):
    vec[i] = -vec[i]
print(vec)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17  18
  19  20]


Write a numpy programme to compute the sum of all elements some of each column and some of each row of a given array.

In [54]:
arr = np.random.rand(4, 5)
arr

array([[0.02245591, 0.49616521, 0.04086152, 0.84039784, 0.13087239],
       [0.38593444, 0.73814152, 0.4306377 , 0.80108468, 0.34430218],
       [0.59220407, 0.50634785, 0.70095769, 0.91627869, 0.66095356],
       [0.22149231, 0.25840895, 0.08289154, 0.67439943, 0.44196552]])

Write a numpy programme to save a given array to a text file and load it.

In [62]:
arr = np.random.rand(2, 3)
arr

array([[0.79893863, 0.26709718, 0.98912475],
       [0.76054655, 0.8282849 , 0.21869616]])

In [63]:
np.savetxt("file.txt", arr)
np.loadtxt("file.txt")

array([[0.79893863, 0.26709718, 0.98912475],
       [0.76054655, 0.8282849 , 0.21869616]])

Write a numpy programme to cheque whether to arrays are equal.

In [66]:
arr1, arr2 = np.array([1, 2, 3, 4]), np.array([1, 2, 2, 3])

np.equal(arr1, arr2)

array([ True,  True, False, False])

Write a numpy programme to create a 4 x 4 array with random values. 
Create a new array from the set array by swapping first and last rows.

In [76]:
np.random.seed(10) # Fix the random values
arr = np.random.rand(4, 4)
print(arr)
print()

arr[[0, 3]] = arr[[3, 0]]
print(arr)

[[0.77132064 0.02075195 0.63364823 0.74880388]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.00394827 0.51219226 0.81262096 0.61252607]]

[[0.00394827 0.51219226 0.81262096 0.61252607]
 [0.49850701 0.22479665 0.19806286 0.76053071]
 [0.16911084 0.08833981 0.68535982 0.95339335]
 [0.77132064 0.02075195 0.63364823 0.74880388]]


Create a numpy programme to multiply two given arrays of same size element by element.

In [75]:
arr1, arr2 = np.array([[1, 2], [3, 4]]), np.array([[2, 4], [6, 8]])

prod = np.array([[0, 0], [0, 0]])
for i in range(2):
    for j in range(2):
        prod[i, j] = arr1[i, j] * arr2[i, j]

prod


array([[ 2,  8],
       [18, 32]])