In [12]:
import numpy as np
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
print(m1)
print(m2)
a=np.linalg.inv(m1)
print(a)
b=np.transpose(m1)
print(b)
c=np.linalg.det(m2)
print(c)
d=np.dot(m1,m2)
print(d)
e=m1.flatten()
print(e)



[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 3]
 [2 4]]
-1.999999999999999
[[19 22]
 [43 50]]
[1 2 3 4]


In [26]:

mat=[]
r=int(input("Enter the no.of rows:"))
c=int(input("Enter the no.of cols:"))
for i in range(r):
    row= []
    for j in range(c):
        
        a=int(input("Enter values:"))
        row.append(a)
    mat.append(row)  
        
print(mat)
x=np.transpose(mat)
print("Tranpose of the matrix is",x)
c=np.linalg.det(m2)
print("Determinant of the matrix is",c)

Enter the no.of rows:2
Enter the no.of cols:2
Enter values:1
Enter values:2
Enter values:3
Enter values:4
[[1, 2], [3, 4]]
Tranpose of the matrix is [[1 3]
 [2 4]]
Determinant of the matrix is -1.999999999999999


In [4]:
import numpy as np
r1=int(input("Enter row:"))
c1=int(input("Enter cols:"))
mat=[]
a=list(map(int,input(" ").split()))
matrix=np.array(a).reshape(r1,c1)
print(matrix)
z1=np.trace(matrix)
z2=matrix.trace()
print(z2)
z3=np.linalg.matrix_rank(matrix)
print(z3)
z4=np.linalg.eig(matrix)
print(z4)


Enter row:2
Enter cols:2
 1 2 3 4
[[1 2]
 [3 4]]
5
2
(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [ ]:
#numpy prgrm to create a vector with values from 0-20 & change the sign of the numbers in the range from 9-15
# sum of all elmnts in arr ,rows , cols also
#write a numpy pgm to save a given array to save a txt file and load it
# check the given 2 arrs equaln or not
# 4x4 arr with random() values ,create a newarr from the setArr by swapping 1st and last rows
#multiply 2 given arrs of same size elmnt by elmnt


In [17]:
import numpy as np
m2=np.arange(0,21)
for i in range(9,21):
        
        if i>=9 and i<=15:
            y=i*-1
            print(y)

-9
-10
-11
-12
-13
-14
-15


In [33]:
m1=np.array([[1,2],[3,4]])
sum1=np.sum(m1)
print(sum1)
print(np.sum(m1,axis=1))# sum of rows
print(np.sum(m1,axis=0))# sum of cols
        

    
    

10
[3 7]
[4 6]


In [42]:
m2=np.array([[1,2],[3,4]])
y=np.savetxt("file.txt",m2)
z=np.loadtxt("file.txt")
print(z)

[[1. 2.]
 [3. 4.]]


In [47]:
m1=np.array([1,2,5,4])
m2=np.array([1,2,3,4])
a=np.equal(m1,m2)
print(a)


[ True  True False  True]


In [66]:
 #4x4 arr with random() values ,create a newarr from the setArr by swapping 1st and last rows
arr = np. random. rand(4, 4)
y=np.round(arr*100)
print(y)
y[[0,-1]]=y[[-1,0]]
print(y)

[[49. 11.  5. 88.]
 [39. 30. 76. 75.]
 [15. 99. 51. 50.]
 [75. 30. 71. 43.]]
[[75. 30. 71. 43.]
 [39. 30. 76. 75.]
 [15. 99. 51. 50.]
 [49. 11.  5. 88.]]


In [47]:
m1=np.array([1,2,5,4])
m2=np.array([1,2,3,4])
a=np.equal(m1,m2)
print(a)


[ True  True False  True]


In [69]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[1,2],[3,4]])
a=np.multiply(m1,m2)
print(a)


[[ 1  4]
 [ 9 16]]
