In [12]:
import numpy as np
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
print(m1)
print(m2)
a=np.linalg.inv(m1)
print(a)
b=np.transpose(m1)
print(b)
c=np.linalg.det(m2)
print(c)
d=np.dot(m1,m2)
print(d)
e=m1.flatten()
print(e)



[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1 3]
 [2 4]]
-1.999999999999999
[[19 22]
 [43 50]]
[1 2 3 4]


In [26]:

mat=[]
r=int(input("Enter the no.of rows:"))
c=int(input("Enter the no.of cols:"))
for i in range(r):
    row= []
    for j in range(c):
        
        a=int(input("Enter values:"))
        row.append(a)
    mat.append(row)  
        
print(mat)
x=np.transpose(mat)
print("Tranpose of the matrix is",x)
c=np.linalg.det(m2)
print("Determinant of the matrix is",c)

Enter the no.of rows:2
Enter the no.of cols:2
Enter values:1
Enter values:2
Enter values:3
Enter values:4
[[1, 2], [3, 4]]
Tranpose of the matrix is [[1 3]
 [2 4]]
Determinant of the matrix is -1.999999999999999


In [32]:
r1=int(input("Enter row:"))
c1=int(input("Enter cols:"))
mat=[]
a=list(map(int,input(" ").split()))
matrix=np.array(a).reshape(r1,c1)
print(matrix)



Enter row:3
Enter cols:3
 1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
